"""sync qualified leads columns

Revision ID: 3d03f9674a0a
Revises: 0b1e5b317871
Create Date: 2026-08-14 17:52:00.939598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d03f9674a0a'
down_revision: Union[str, Sequence[str], None] = '0b1e5b317871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analyses', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.drop_constraint('ai_analyses_qualified_lead_id_fkey', 'ai_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'ai_analyses', 'qualified_leads', ['qualified_lead_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ai_analyses', 'score')
    op.add_column('qualified_leads', sa.Column('name', sa.String(), nullable=False))
    op.add_column('qualified_leads', sa.Column('website', sa.String(), nullable=True))
    op.add_column('qualified_leads', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('qualified_leads', sa.Column('location', sa.String(), nullable=True))
    op.add_column('qualified_leads', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('qualified_leads', sa.Column('email', sa.String(), nullable=True))
    op.add_column('qualified_leads', sa.Column('source', sa.String(), nullable=True))
    op.add_column('qualified_leads', sa.Column('lead_score', sa.Integer(), nullable=True))
    op.add_column('qualified_leads', sa.Column('qualified_at', sa.DateTime(), nullable=False))
    op.drop_constraint('qualified_leads_business_id_fkey', 'qualified_leads', type_='foreignkey')
    op.create_foreign_key(None, 'qualified_leads', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_column('qualified_leads', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualified_leads', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'qualified_leads', type_='foreignkey')
    op.create_foreign_key('qualified_leads_business_id_fkey', 'qualified_leads', 'businesses', ['business_id'], ['id'])
    op.drop_column('qualified_leads', 'qualified_at')
    op.drop_column('qualified_leads', 'lead_score')
    op.drop_column('qualified_leads', 'source')
    op.drop_column('qualified_leads', 'email')
    op.drop_column('qualified_leads', 'phone')
    op.drop_column('qualified_leads', 'location')
    op.drop_column('qualified_leads', 'industry')
    op.drop_column('qualified_leads', 'website')
    op.drop_column('qualified_leads', 'name')
    op.add_column('ai_analyses', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ai_analyses', type_='foreignkey')
    op.create_foreign_key('ai_analyses_qualified_lead_id_fkey', 'ai_analyses', 'qualified_leads', ['qualified_lead_id'], ['id'])
    op.drop_column('ai_analyses', 'ai_score')
    # ### end Alembic commands ###
