"""add lead qualification fields

Revision ID: 49a2088b78f3
Revises: ae22870c6146
Create Date: 2026-08-11 21:47:10.210773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49a2088b78f3'
down_revision: Union[str, Sequence[str], None] = 'ae22870c6146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "businesses",
        sa.Column(
            "lead_score",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "businesses",
        sa.Column(
            "qualification",
            sa.String(),
            nullable=False,
            server_default="unqualified",
        ),
    )

    # Remove server defaults after existing rows are populated.
    op.alter_column(
        "businesses",
        "lead_score",
        server_default=None,
    )

    op.alter_column(
        "businesses",
        "qualification",
        server_default=None,
    )
    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'qualification')
    op.drop_column('businesses', 'lead_score')
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='notes_business_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notes_pkey')
    )
    op.create_index('ix_notes_business_id', 'notes', ['business_id'], unique=False)
    # ### end Alembic commands ###
