"""create notes table

Revision ID: 9fd9606e66c4
Revises: 34eb3c489444
Create Date: 2026-08-14 15:07:57.162389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fd9606e66c4'
down_revision: Union[str, Sequence[str], None] = '34eb3c489444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analyses', sa.Column('score', sa.Integer(), nullable=True))
    op.alter_column('ai_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('ai_analyses_qualified_lead_id_fkey', 'ai_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'ai_analyses', 'qualified_leads', ['qualified_lead_id'], ['id'])
    op.drop_column('ai_analyses', 'updated_at')
    op.drop_column('ai_analyses', 'ai_score')
    op.add_column('qualified_leads', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint('qualified_leads_business_id_fkey', 'qualified_leads', type_='foreignkey')
    op.create_foreign_key(None, 'qualified_leads', 'businesses', ['business_id'], ['id'])
    op.drop_column('qualified_leads', 'source')
    op.drop_column('qualified_leads', 'industry')
    op.drop_column('qualified_leads', 'phone')
    op.drop_column('qualified_leads', 'location')
    op.drop_column('qualified_leads', 'website')
    op.drop_column('qualified_leads', 'qualified_at')
    op.drop_column('qualified_leads', 'lead_score')
    op.drop_column('qualified_leads', 'name')
    op.drop_column('qualified_leads', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualified_leads', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('qualified_leads', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('qualified_leads', sa.Column('lead_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('qualified_leads', sa.Column('qualified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('qualified_leads', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('qualified_leads', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('qualified_leads', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('qualified_leads', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('qualified_leads', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'qualified_leads', type_='foreignkey')
    op.create_foreign_key('qualified_leads_business_id_fkey', 'qualified_leads', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_column('qualified_leads', 'created_at')
    op.add_column('ai_analyses', sa.Column('ai_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_analyses', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ai_analyses', type_='foreignkey')
    op.create_foreign_key('ai_analyses_qualified_lead_id_fkey', 'ai_analyses', 'qualified_leads', ['qualified_lead_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ai_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('ai_analyses', 'score')
    # ### end Alembic commands ###
