"""create proposals table

Revision ID: bee8573a8cf8
Revises: 667f4e5a3da5
Create Date: 2026-08-14 20:40:52.128476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee8573a8cf8'
down_revision: Union[str, Sequence[str], None] = '667f4e5a3da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualified_lead_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('greeting', sa.String(), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('identified_problem', sa.Text(), nullable=True),
    sa.Column('proposed_solution', sa.Text(), nullable=False),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('call_to_action', sa.Text(), nullable=False),
    sa.Column('closing', sa.Text(), nullable=False),
    sa.Column('full_proposal', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qualified_lead_id'], ['qualified_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_index(op.f('ix_proposals_qualified_lead_id'), 'proposals', ['qualified_lead_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_qualified_lead_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###
